### ISSUE TITLE
undefined is not a function error throws when respond or flush[with buffer] is called

### ISSUE THREAD

**Issue by ramyav** [kbaltrinic/http-backend-proxy#1]
Hi , I have downloaded the proxy using  'npm install  http-backend-proxy' and in my test file i have set  
 HttpBackend = require('http-backend-proxy');
 proxy = new HttpBackend(browser);

when i do 
res = proxy.whenGET('/api/v2/catalog/') 
,and try to console output the 'res' variable I get the respond and passThrough functions which is correct but at the same time if i do 
res = proxy.whenGET('/api/v2/catalog/').respond(200);
and console output it res is getting resolved with 
{ then: [Function: then],
  cancel: [Function: cancel],
  isPending: [Function: isPending] }

but i get this ERROR on the line where respond is called.
Stacktrace:
     UnknownError: unknown error: undefined is not a function
  (Session info: chrome=35.0.1916.114)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.9.2 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 87 milliseconds
Build info: version: '2.41.0', revision: '3192d8a', time: '2014-03-27 17:17:32'
==== async task ====
WebDriver.executeScript()
    at executeOrBuffer (/Users//projects/projectname/node_modules/http-backend-proxy/test/lib/http-backend-proxy.js:65:22)
    at Object.respond (/Users//projects/projectname/node_modules/http-backend-proxy/test/lib/http-backend-proxy.js:46:18)
    at null.<anonymous> (/Users//projects/projectname/test/client/preview-card/ew-383.step.js:22:10)
==== async task ====
Asynchronous test function: beforeEach()
Error
    at null.<anonymous> (/Users//projects/projectname/test/client/preview-card/ew-383.step.js:12:3)
    at Object.<anonymous> (/Users//projects/projectname/test/client/preview-card/ew-383.step.js:1:63)

Also providing below  the script for the 'proxy.whenGET('/api/v2/catalog/').respond(200);' that has been passed through the  executeOrBuffer(script) function.

var el = document.querySelector("body");      angular.element(el).injector().invoke(function($httpBackend){      $httpBackend.context={};$httpBackend.whenGET("/api/v2/catalog/assets/79e50971-9a09-4814-8471-11e20d40fc0b?artwork=art220x326").respond("200");});

I have also tried using buffer:true and using proxy.flush but again it fails with the same error on the line proxy.flush(). Not sure what am doing wrong as i have set everything according to the wiki

**Comment by jairovsky** [comment]
The most non-intrusive way I found was to do the following:

- Add ```angular-mocks.js``` on my development HTML (this will be replaced by a ```gulp``` build later).

- Leverage Protractor's ```addMockModule``` to push ```ngMockE2E``` dependency into my module in test:
```js
  var HttpBackend = require('http-backend-proxy');

  describe('Login page', function () {

    browser.addMockModule('login', function () {
      angular.module('login').requires.push('ngMockE2E');
    });

    it("should do my very neat login stuff here", function () {

      browser.get('/login.html');

      var proxy = new HttpBackend(browser);
```
I still struggle to find a way to inject ```angular-mocks.js``` into the HTML instead of declaring it, though.
