### ISSUE TITLE
TypeError: undefined is not a function in proxy.whenGet()

### ISSUE THREAD

**Issue by phaggood** [kbaltrinic/http-backend-proxy#13]
i have a simple test that won't recognize whenGET from Httpbackend; it's not barfing on the require('Httpbackend') so I know it's finding the library.

    var HttpBackend = require('http-backend-proxy');
    var proxy = new HttpBackend(browser, {buffer: true});
    var loginpage = require('./pages/login.page.js');
    var loginUser = {
    "_id": 33,
    "username": "tlouisa",
    "token": "{5D0A97C1-8659-4995-A8F3-31E20BA46AE9}",
    "person": {"name": "Thelma Louisa"},
    "address": "123 Main Street",
    "credentialList": [],
    "services": []
    };

    describe('login', function () {

    var page;

    beforeEach(function () {
        page = new loginpage();
    });

    beforeEach(function () {
        browser.ignoreSynchronization = true;
    });

    it('should go to mainmenu after successful login', function () {
        proxy.whenGet(/^\/login\//).respond(200,loginUser);  <-- error on this line *****
        proxy.whenGet(/^\/templates\//).passThrough();
        proxy.whenGet(/^\/shifts\//).passThrough();

        browser.executeScript("localStorage.removeItem('activeUser');");
        page.username.sendKeys('tlouisa');
        page.loginButton.click();
        browser.sleep(2000);
        expect(browser.getCurrentUrl()).toEqual('http://localhost:8100/#/mainmenu');
        browser.sleep(2000);
    });
});

**Comment by phaggood** [comment]
Gah!  Nevermind, stupid mistake.  Close this.

**Comment by kbaltrinic** [comment]
`proxy.whenGet` vs `proxy.whenGET`?
