### ISSUE TITLE
No Mocking Unless Original Request Returns 200 OK

### ISSUE THREAD

**Issue by zalow517** [kbaltrinic/http-backend-proxy#15]
Hi and thank you for this module!

I've found it very useful, but lately I have noticed that whenever the request I am mocking doesn't go through (does not return 200 OK), then the mocking doesn't occur.

Is this a know issue or can it be solved in some way?

I am calling all my mocks from Protractor's configuration file using the onLoad.whenGET()... respond() way.

**Comment by kbaltrinic** [comment]
Zalow, sorry for the delayed response.  I've been on vacation.  I am afraid I don't quite understand the situation.  Its the mock that determines whether a 200 OK or some other status code is returned, is it not?  So how is it that mocking isn't occurring?

**Comment by kbaltrinic** [comment]
@zalow517 Are you still having an issue or can I close this?
