### ISSUE TITLE
Different response return when caching is enabled

### ISSUE THREAD

**Issue by rfodge** [kbaltrinic/http-backend-proxy#18]
Hi,

I have an angular js application that i'm using http-backend-proxy to try to mock the backend.  It is using an angular cache factory (DSCacheFactory).  When i disable the caching, everything works fine.  When the cache is enabled, the format of the response being returned is different from the first call to the second call.  In my tests, the initial page loads containing a list of messages.  The messages are what I mocked and on the initial load they load fine.  I go to another page (settings) then go back to the messages back and it fails.  It fails because the data retrieved is now in a different format.  

I added console statements to debug which shows the difference in the data:
On initial load:
![image](https://cloud.githubusercontent.com/assets/11653643/9549170/ad4d7f20-4d72-11e5-9521-e099b2c29513.png)

On second attempt:
![image](https://cloud.githubusercontent.com/assets/11653643/9549198/ca6b0398-4d72-11e5-8465-fcef62d78d9a.png)

Since there is no messages array in the second attempt, it fails.  

Does anyone know why this is occurring or how to fix?  

Thanks!

**Comment by kbaltrinic** [comment]
Sorry for the delay.  At first glance, this does not seem like an issue with the proxy.  However, I would need a working example in order to be able to dig into it further.

**Comment by rfodge** [comment]
Thanks, I'm not sure if I will be able to break down our project code enough to come up with an example but i will see what i can come up with!

**Comment by kbaltrinic** [comment]
@rfodge, did you ever resolve this issue?  Can it be closed or should it be left open?

**Comment by rfodge** [comment]
Hi,
I didn't resolve.  We disabled the cache in our tests to get around it.  I am unable to come up with an example for you though so if you want to close and reopen if someone else encounters it, that works for me. Thanks -
