### ISSUE TITLE
Mocked request not being updated

### ISSUE THREAD

**Issue by rfodge** [kbaltrinic/http-backend-proxy#20]
Hi,

I am trying to update the data returned for a call within a test using the syncContext.

I do something like this:
proxy.context = {
      notes: notifications,
      messages: allMessages
    };

notifications and all messages are json objects that i pull in by doing:
var notifications = require('../fixtures/notifications.json');

proxy.when('GET', '...notificationsURL...').respond(200, proxy.context.notes);

The first time the call is made the correct data is loaded.

Before the second call is made I do,
proxy.syncContext({
      notes: notifications2,
      messages: messages2
});

When I print the values to the console, the correct values are displayed:
console.log(proxy.context.notes);
console.log(proxy.context.allconvos);

However, the next time the call is made, the original data is returned, not the data that I updated using SyncContext.

Is there something else I need to be doing?

Thanks!

**Comment by mradionov** [comment]
I guess respond should receive a function as a second parameter to use context feature, like it is shown here in the docs - [Using context object](https://github.com/kbaltrinic/http-backend-proxy#using-the-context-object). 

```
proxy.context = {
    notes: notifications,
    messages: allMessages
};

proxy.when('GET', '...notificationsURL...').respond(200, function () {
    return [200, $httpBackend.context];
});

// make a first call

proxy.context = {
    notes: notifications2,
    messages: allMessages2
};
proxy.syncContext();

// make a second call
```

**Comment by rfodge** [comment]
Looking more at the httpBackend documentation, I think I might need to do something like:

handler = proxy.when('GET', '...notificationsURL...').respond(200, proxy.context.notes);
....
make first call
....
handler.respond(proxy.context.notes)
....
make second call

But still haven't had luck yet.

**Comment by mradionov** [comment]
You are not using *httpBackend*  directly here, you are using it through a proxy library - *http-backend-proxy*, and you have to consider it's features. Your example won't work, because it was not implemented yet ([see related PR](https://github.com/kbaltrinic/http-backend-proxy/pull/10))

**Comment by rfodge** [comment]
Oh ok thanks for the quick response.  Do you think I should just use httpBackend directly then?  What would be the downfalls on just using that instead and override the calls that way?

**Comment by rfodge** [comment]
sorry, forgot to add that I tried the function but then my data never seems to get returned (on the first call).  I put the following:
proxy.when('GET', '....url....').respond(function () {
      return [200, proxy.context.notes];
    });

**Comment by rfodge** [comment]
I got it!  I had to change proxy to $httpBackend and now it is working.  Thanks so much for your help.  I never would have figured that out!

**Comment by mradionov** [comment]
Glad it helped. Feel free to close this issue then, if it worked for you. I'll copy the solution [back to StackOverflow](http://stackoverflow.com/questions/32785436/updating-mocked-objects-in-protractor-tests), where everything started.

**Comment by rfodge** [comment]
I opened a new issue if you have any suggestions on that as well!: https://github.com/kbaltrinic/http-backend-proxy/issues/21
