### ISSUE TITLE
2nd test fails when using mocked calls

### ISSUE THREAD

**Issue by rfodge** [kbaltrinic/http-backend-proxy#21]
Hi,

I have 2 tests within my protractor spec file.  I do the setup of the mocked calls in the beforeEach() as shown below.  Each test will pass when ran individually, but it will fail on the 2nd test if I run both.  

beforeEach(function () {
    httpBackend = new HttpBackend(browser);

    httpBackend.onLoad.when('GET', /scripts.*/).passThrough();
    httpBackend.onLoad.when('GET', /views.*/).passThrough();
    .....all of the onLoad calls...... 
    browser.get(browser.params.route);

    httpBackend.when('GET', /images.*/).passThrough(); 
    httpBackend.when('GET', '....URL....').respond(function () {
              return [200, $httpBackend.context.conversations];
            });
    .....all of the calls to load......

    login to application
})

afterEach(function(){
   logout of application
   httpBackend.onLoad.reset();
})

it ('test 1', function(){
    .....
})

it ('test 2', function(){
    .....
})

Thanks -

**Comment by rfodge** [comment]
I moved the following lines to a beforeAll function instead and now it looks like it is working.  I don't understand why it works though or if it is the correct approach to fix so if someone could explain that for me, i'd appreciate it!
beforeAll(function(){
    httpBackend = new HttpBackend(browser);
    ...all of the onload calls....
    browser.get(browser.params.route);
  })

I thought with protractor tests browser.get() should get called before each test.

**Comment by kbaltrinic** [comment]
Calling browser.get() reloads the page under test in the browser.  With in-browser-apps, this has the effect unloadng and restarting the entire app.  Therefore, if your second test assumes that app to be in the state that the first test left it in, calling browser.get() would have blown away that state.  

Its not clear from your example snippets if that is the case or not.  I am just speculating.  If not, if you can provide a link to a complete example I can try to help.

**Comment by rfodge** [comment]
Hi,

Thanks for your response!  I had the beforeEach(), shown above in first comment, create the instance of httpbackend-proxy, create all the onLoad calls, and the afterLoad calls.  The second test does not depend on the state of the first test. It just depends on the mocking being set up (so everything I had in the beforeEach).  The only difference between the two test would that one would be called upon browser launch and the other is on a page refresh.  (they both would begin at the login page).  It just doesn't see the calls as being mocked out on the page reload for some reason? even though the beforeEach would go through the same set of actions for each test.

From what i can tell someone else may have had the same or similar issue as noted here:
http://stackoverflow.com/questions/31065846/why-subsequent-tests-for-ngmocke2e-failed-to-call-mock-backend-only-the-first-t/32809998?noredirect=1#comment53461597_32809998

Let me know if you still need an example.  I will have to see what I would be able to come up with.

**Comment by rfodge** [comment]
Maybe this will help, here is a simple example of code for what is happening:

![image](https://cloud.githubusercontent.com/assets/11653643/10126324/121d5ecc-655e-11e5-92b4-7ea188979aaf.png)

When the second test runs, this is the error I am seeing in the browser console:
![image](https://cloud.githubusercontent.com/assets/11653643/10126343/598c76e4-655e-11e5-97aa-6f9cd715eb10.png)

So all this does is open the site to the login page, then it will reload it again for the 2nd test.

**Comment by kbaltrinic** [comment]
I think the issue here may be that you are creating a new proxy for every test, and using the onLoad feature, but you are not calling .onload.reset() in your test clean-up after every test.  Per the docs, if you use onLoad, you will want to reset it when you are done.  In you case, done means before you loose the reference to each instance of the proxy.  Otherwise you are leaving the underlying browser object in an invalid state.

**Comment by kbaltrinic** [comment]
Another point which isn't relevant to your problem (or I don't think it is) is that you shouldn't need to set up the calls twice.  Setting them up in onLoad before the get is sufficient.  They will still be in place for later use as well.

**Comment by rfodge** [comment]
Hi, thanks for your follow-up.   I added the onload.reset() but still have the same errors in the console.  Here is what I updated it to:

![image](https://cloud.githubusercontent.com/assets/11653643/10285766/4ebe0dc2-6b58-11e5-9c41-cf4b1fe680e8.png)

**Comment by rfodge** [comment]
should i create the instance of the proxy outside of the beforeEach then?  I thought when looking at examples, it was done in the beforeEach.

**Comment by kbaltrinic** [comment]
If by example you are referring to the e2e onload test, if you look closely you will see that though it is in the beforeEach() it is wrapped in an `if (firstRun) {...}` conditional (because jasmine does not natively support beforeAll).  It seems to me that what you are doing should work, but it certainly wouldn't hurt to try the other approach.

**Comment by rfodge** [comment]
Ok thanks! I'll try moving it to see if it makes a difference.

**Comment by rfodge** [comment]
OK, trying this again.  I moved this portion to the onPrepare function in the protractor conf file:

![image](https://cloud.githubusercontent.com/assets/11653643/11997032/39d96e9e-aa3f-11e5-9242-ae45975714c6.png)

This works:
![image](https://cloud.githubusercontent.com/assets/11653643/11997036/4477440c-aa3f-11e5-9f66-f512dd2dd591.png)

This does NOT work:
![image](https://cloud.githubusercontent.com/assets/11653643/11997038/55434df8-aa3f-11e5-82a7-52df3d2dda33.png)


When the refresh occurs, it does not act if anything is mocked still.  How can I refresh the page and still have the mocks be used.  I also tried this but the 2nd test fails:
![image](https://cloud.githubusercontent.com/assets/11653643/11997048/9bb4c302-aa3f-11e5-996f-bc4a6ef30146.png)

**Comment by rfodge** [comment]
Also tried doing this:
![image](https://cloud.githubusercontent.com/assets/11653643/11997105/f94c0a9c-aa40-11e5-96fc-840f756dc4e2.png)

**Comment by kbaltrinic** [comment]
Assuming in the above that your beforeEach are not really empty but are setting up the proxy per your original post, I am not seeing anything obvious.  I am afraid you will either need to dig in an debug the issue or provide an example repo that I can use to reproduce and debug on my end.

**Comment by rfodge** [comment]
I set up the proxy as before except in the onPrepare function (that is what mocksPage.onLoad does).  It would look like this if I didn't have it in a function:
![image](https://cloud.githubusercontent.com/assets/11653643/12051030/79dd822e-aecb-11e5-8a1e-00d0694d79b4.png)


I don't have an example application that instantiates ngMockE2E that I can use to show you argh.  

Is there something that needs to be done after you do a browser refresh or browser.get() again in order for it to know to use the mocks?

**Comment by rfodge** [comment]
So I did more investigation and I actually think the brower.ignoreSynchronization is causing the issue.  

Here is what I have in the protractor conf file now in the onPrepare method:
![image](https://cloud.githubusercontent.com/assets/11653643/12054743/f1caa2ee-aef3-11e5-9f36-7885b92947a0.png)

Here is the spec file now, which if I have the browser.ignoreSynchronization commented out, it works.  If I add it in, it fails to load the mocks for the 2nd test:
![image](https://cloud.githubusercontent.com/assets/11653643/12054772/3530ed2c-aef4-11e5-9496-0773cf6d5d12.png)


We currently have to use ignoreSynchronization on our login screen because of issues using a timeout method.  If we don't, it takes approx. 30 seconds for it to identify the elements on the page.

Thoughts on why this occurs or any workaround?

**Comment by kbaltrinic** [comment]
So yes, now that you point it out, that could indeed be the problem.  The [docs for ignoreSyncronization](https://github.com/angular/protractor/blob/9891d430aff477c5feb80ae01b48356866820132/lib/protractor.js#L158) suggest what is likely going on.  In particular "[Using ignoreSyncronization] can be harmful because Protractor will not wait until ... $http calls have been processed."

This is an issue outside of the scope of the proxy.  You are in a difficult testing scenario where you will need to come up with your own mechanism for delaying execution of the tests (but not the onLoad) until the page is really ready.

**Comment by rfodge** [comment]
Thanks for your feedback!  I'll close this issue since its unrelated to the proxy.
