### ISSUE TITLE
Any insight on JSON-RPC services?

### ISSUE THREAD

**Issue by xlozinguez** [kbaltrinic/http-backend-proxy#22]
Hey @kbaltrinic, I just wanted to pick your mind about using http-backend-proxy for JSON-RPC calls...

JSON-RPC are solely POST calls with a specified `method` and `params` (see http://webob.readthedocs.org/en/latest/jsonrpc-example.html)... so it's pretty hard to differentiate one call from another...

It would be great to see what you think...Thank you!

**Comment by kbaltrinic** [comment]
Yep so this isn't specific to the proxy, this is the same issue even if you are using the http-backend by itself.  I am afraid there is no magic here to help you.  

You have two options.  One is to write a response fuction that parses the `data` argument back to JSON and then evaluates it and does the right thing.  That is probably the best approach, esp. if you want to validate that the right JSON is being passed to the back end.  If you just want to get the back end to return different responses to different tests, and ignore the input sent, then you could use a simpler response function that just returns a value defined on the context object.  Then all you need to do is modify and manually sync the context object between tests.
