### ISSUE TITLE
Is it possible to navigate without browser.get and still invoke whenGET?

### ISSUE THREAD

**Issue by CorwinMoyne** [kbaltrinic/http-backend-proxy#23]
The application I am working on creates a new session when the application loads (to allow deep linking). This means browser.get, although it returns the required mock data, causes the page being got to start a new session. If I get protractor to click my search button, the application works like it does in a real environment and navigates to the new page without refreshing, however whenGET is not invoked and live data is returned from the api.

**Comment by kbaltrinic** [comment]
Sorry for the delay in replying.  Are you seeing any errors in the browser console output?  (There are techniques documented various to capturing that output when running protractor tests).  My guess would be that the ngMockE2E is not loading.  Either this or you have a passThrough that is being unintentionally invoked (its overly broad) etc.

**Comment by kbaltrinic** [comment]
@CorwinMoyne Are you still having issues with this or can I close this ticket?

**Comment by CorwinMoyne** [comment]
I thought I got back to you already. Sorry about that. Not having issues anymore. All sorted.
