### ISSUE TITLE
whenGET function doesn't get called!

### ISSUE THREAD

**Issue by ramanbhati** [kbaltrinic/http-backend-proxy#24]
In my application, I am trying to mock backend data on GET request. I have already written code to initiate http-backend-proxy, defined onload functions and added mock json data in my app. But when I try to run the app and API call is made, the proxy.onload.whenGET function would not get executed. I don't know where am I doing wrong. Can you please give me any pointer to solve my problem?

**Comment by kbaltrinic** [comment]
Do you have an example app I can look at?  You might also take a look at some of the closed issues to see some of the typical problems people encounter and the resolutions.

**Comment by ramanbhati** [comment]
Thanks for replying. Yes, I am sharing the example app here. 

        httpBackend = require('http-backend-proxy');
        mockInventoryData = require('../data/devicesInventory.json');
        proxy = new httpBackend(browser);
        proxy.onLoad.reset();
        var proxy, httpBackend, mockFastProvisionData;
        page = require('./pages/homePage.js');
        homePage = new page();
        proxy.onLoad.whenGET('/ui/devices').respond(function(status, data) {
            return [200, mockInventoryData];
        });
        browser.ignoreSynchronization = true;

      it('should pass if the user_name and comments fields ARE associated with the device', function() {
             browser.get('http://localhost:9009/#/devices');
             expect(homePage.someFunc()).toBeDefined();


The someFunc() makes a http call to /ui/devices. 

Please let me know if I can help you by providing more information.

**Comment by kbaltrinic** [comment]
I see this is closed, but adding some comments based on the example provided for those it may help.  There are a few possible issues here.  
 1. First, it appears that httpBackend is being declared twice. This may just be a cut/paste error and I'll assume that the `var proxy...` declaration is really at the top of the file.
 1. Remember that the `whenGet` function actually runs on the browser and therefore will not have access to the `mockInventoryData` unless it is placed on the Context ([see the docs](https://github.com/kbaltrinic/http-backend-proxy/wiki/Installation-&-Usage#calling-functions-and-sharing-data-between-tests-and-browser)).
 1. `ingoreSyncronization` can cause problems with stuff executed via onLoad.  See issue #21, especially the last few comments.
