### ISSUE TITLE
How can we mock two responses for same request i.e, one on page load and other one on page request.

### ISSUE THREAD

**Issue by Rakesh5530** [kbaltrinic/http-backend-proxy#26]
I have a scenario where I need to mock a http request two times. i.e., on page load it should return 401 status and on page when I fill the username, password and click on login button, it will request the same url and should return 200 status.

Below is the code snippet:

```
proxy.onLoad.when('GET','http://localhost:8080/login')
            .respond(function(method, url){return [401,{"message":"Authorization has been denied for this request."}];});

browser.get('http://localhost:8888');

proxy.when('GET','http://localhost:8080/login')
            .respond(function(method, url){return [200,{"message":"Authorization has been sucess for this request."}];});
```

I'm getting same response for onload and onpage request i.e., 401 status.

Please let me know how can I mock such scenario's.

**Comment by kbaltrinic** [comment]
This has nothing to do with the proxy but is a httpBackend question.  However the short answer is that you can't assign multiple response functions to the same endpoint.  You have to assign one response function the does what you want, namely return `[401,{"message":"Authorization has been denied for this request."}]` the first time it is called and `[200,{"message":"Authorization has been sucess for this request."}]` the second time.
