### ISSUE TITLE
Failing with Protractor v5.0

### ISSUE THREAD

**Issue by rfodge** [kbaltrinic/http-backend-proxy#32]
See http://stackoverflow.com/questions/42564200/protractor-version-5-0-http-backend-proxy-failing for more detailed information.

**Comment by sri85** [comment]
@kbaltrinic Is there a workaround for this issue?

**Comment by rfodge** [comment]
Hi @sri85, please see: https://github.com/angular/protractor/issues/4249

Protractor provided a workaround.
