### ISSUE TITLE
How to change already mocked requests

### ISSUE THREAD

**Issue by szimek** [kbaltrinic/http-backend-proxy#5]
I don't really understand the difference between `onLoad.when` and  `when` and how can I overwrite already mocked request for specific test. I'm mocking "sign in" request with a JSON response using `onLoad` and then try to modify the response in a specific test:

``` ruby
# http_backend.coffee
...
proxy.onLoad
    .when("POST", "#{proxy.api}/login.json", user: {email: "alice@doe.com", password: "secret"})
    .respond(201, require("./responses/v2/successful_login.json"))

# test.coffee
proxy  = require("./support/http_backend")

describe "Something", ->
  it "changes previously mocked request", ->
    response = require("./support/responses/v2/successful_login.json")
    response.user.locale = 'es'
    proxy.onLoad
      .when("POST", "#{proxy.api}/login.json", user: {email: "alice@doe.com", password: "secret"})
      .respond(201, response)

    browser.get("/")
    ...  
```

Should it work or should I do it somehow differently?

**Comment by szimek** [comment]
Hi, a short follow up question :) We have a few default request mocks common for all tests and if some test needs to change one of these mocks, it needs to call `proxy.onLoad.reset()` and then set some of these common mocks again, which makes tests a bit more complex and less readable.

Would it be possible to simply make it so that the next call to `proxy(.onLoad).when` overwrites (or has a priority over) the previous mock with the same method/URL? It looks like `$httpBackend` [adds new mock definitions to the end of definitions array](https://github.com/angular/angular.js/blob/g3_v1_4/src/ngMock/angular-mocks.js#L1251), thus when iterating over them to find a match, it finds the ones mocked earlier first. Wouldn't it be better idea to either iterate from the end of definitions array of put new mocks at the beginning of it?

**Comment by kbaltrinic** [comment]
I am generally in agreement with you that a last-in-wins approach would be better.  However $httpBackend is not part of this project's codebase.  Its part of the angular framework.  The proxy is just that, a proxy that gives in-test access to angular's in-browser mocking capabilities.  I can't modify those capabilities.

**Comment by kbaltrinic** [comment]
Sorry I replied w/o first rereading the original thread, so let me say a bit more thats likely more relevant. 

It is possible that the proxy could send the cached calls to the browser in the reverse order.  I have played with that idea, but my guiding approach as been to be just a proxy and not do anything that attempts to modify the behavior of the $httpBackend object.  I have taken this approach for several reasons.  I think the biggest one is simply separation of concerns.  The proxy is just a proxy.  The proxied service is responsible for functionality.  Derivative concerns are the confusion (and associated support effort) that would ensue if I started tinkering with that sort of stuff.  

That said, I am open to people submitting pull request that add this sort of thing as optional functionality that can switched on via the options object in the proxy constructor.  It just has to be that the proxy provides the standard behavior by default and these optional behaviors are "use at your own risk".

**Comment by kbaltrinic** [comment]
A final P.S.  Depending on what you are trying to do, if you want to modify the results that a particular endpoint returns between tests, while leaving other calls in place, see [the docs on the context object](https://github.com/kbaltrinic/http-backend-proxy/wiki/Installation-&-Usage#calling-functions-and-sharing-data-between-tests-and-browser).  In particular the examples under [manually synchronized contexts](https://github.com/kbaltrinic/http-backend-proxy/wiki/Installation-&-Usage#manually-synchronizing-contexts) discuss how to do just that in a very flexible way.

**Comment by szimek** [comment]
Thanks! I should've been more clear - I know that this library is just a proxy, but I was expecting an answer like: "It wouldn't work, because in such and such scenario it would break this and that" :) Otherwise I'm not really sure why $httpBackend.when method works like it does and why nobody has complained about it yet. I'll probably just change `definitions.push(definition)` to `unshift` and see if it breaks anything.

Anyway, in case it doesn't work - how would the context help in such case? As far as I understand it, I need to define what would happen depending on the context when mocking the response, e.g.:
```coffeescript
proxy.onLoad.when("GET", "/foo").respond (method, url) ->
  if $httpBackend.context.true
    [200, foo: true]
  else
    [200, foo: false]
```
so if I'm creating the default mocks, they'd need already be somehow aware of possible context values.

**Comment by kbaltrinic** [comment]
So with the context object, in your above example, you simplify things to: 
    proxy.onLoad.when("GET", "/foo").respond (method, url) ->
      [200, $httpBackend.context.foo]

Then before each test you can simply assign whatever value you want returned to `foo` and re-synchronize the context.

**Comment by szimek** [comment]
Thanks! For now we've modified `$httpBackend.when` to use `unshift` instead of `push`, simplified our tests a lot and they still pass :)
